# Generated by Django 4.0.6 on 2022-08-31 10:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='con',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drink',
            name='con',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
