# Generated by Django 4.0.6 on 2022-09-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_dish_con_drink_con'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('pic', models.ImageField(upload_to='menu/Dish')),
                ('con', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Risotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('pic', models.ImageField(upload_to='menu/Dish')),
                ('con', models.TextField()),
            ],
        ),
    ]
